import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";

assert.ok(existsSync("src/lib/image-providers/apimart.ts"));
assert.ok(existsSync("src/lib/image-providers/openai-compatible.ts"));

const openaiSource = readFileSync("src/lib/openai.ts", "utf8");
const apimartSource = readFileSync("src/lib/image-providers/apimart.ts", "utf8");
const compatSource = readFileSync("src/lib/image-providers/openai-compatible.ts", "utf8");
const envExampleSource = readFileSync(".env.example", "utf8");

assert.match(openaiSource, /IMAGE_PROVIDER/);
assert.match(openaiSource, /generateWithApimart/);
assert.match(openaiSource, /generateWithOpenAICompatible/);
assert.match(openaiSource, /provider === "apimart"/);
assert.match(openaiSource, /const remoteImageUrl = await generateWithApimart/);
assert.match(openaiSource, /if \(remoteImageUrl\)/);
assert.match(openaiSource, /return persistGeneratedImage\(\{ localFilePath: filepath, localImageUrl, filename \}\)/);

assert.match(apimartSource, /APIMART_API_KEY/);
assert.match(apimartSource, /APIMART_BASE_URL/);
assert.match(apimartSource, /APIMART_MODEL/);
assert.match(apimartSource, /gpt-image-2/);
assert.match(apimartSource, /DEFAULT_TIMEOUT_MS = 300_000/);
assert.match(apimartSource, /POLL_INTERVAL_MS = 1000/);
assert.match(apimartSource, /APIMART_GENERATION_MAX_ATTEMPTS = 2/);
assert.match(apimartSource, /APIMart 任务排队超时/);
assert.match(apimartSource, /selectedModel/);
assert.match(apimartSource, /function resolveApimartModel/);
assert.match(apimartSource, /return model \|\| process\.env\.APIMART_MODEL \|\| "gpt-image-2"/);
assert.doesNotMatch(apimartSource, /APIMART_GPT_IMAGE_2_MODEL/);
assert.doesNotMatch(apimartSource, /official_fallback/);
assert.match(apimartSource, /function isRetryableApimartError/);
assert.match(apimartSource, /getImageModelConfig/);
assert.match(apimartSource, /\/images\/generations/);
assert.match(apimartSource, /\/tasks\/\$\{taskId\}/);
assert.match(apimartSource, /resolution = "1k"/);
assert.match(apimartSource, /formatApimartResolution/);
assert.match(apimartSource, /model\.startsWith\("gemini-3\.1-flash-image-preview"\)/);
assert.match(apimartSource, /resolution\.toUpperCase\(\)/);
assert.match(apimartSource, /supportsResolution \? \{ resolution: requestResolution \}/);
assert.doesNotMatch(apimartSource, /\{\s*resolution:\s*"1k"\s*\}/);
assert.match(apimartSource, /formatApimartSize/);
assert.match(apimartSource, /aspectRatioOption === "auto"/);
assert.match(apimartSource, /inferredAspectRatio \|\| "1:1"/);
assert.match(apimartSource, /size:\s*requestSize/);
assert.doesNotMatch(apimartSource, /size:\s*aspectRatioOption/);
assert.match(apimartSource, /quality = "low"/);
assert.match(apimartSource, /supportsQuality \? \{ quality \}/);
assert.doesNotMatch(apimartSource, /quality:\s*"medium"/);
assert.match(apimartSource, /n:\s*1/);
assert.match(apimartSource, /const endpoint = "\/images\/generations"/);
assert.doesNotMatch(apimartSource, /\/images\/edits/);
assert.match(apimartSource, /new FormData\(\)/);
assert.match(apimartSource, /formData\.append\(\s*"file"/);
assert.match(apimartSource, /normalizeReferenceImageForUpload/);
assert.match(apimartSource, /sharp\(imageBuffer,\s*\{ pages: 1 \}\)/);
assert.match(apimartSource, /APIMART_UPLOAD_MAX_BYTES = 20 \* 1024 \* 1024/);
assert.match(apimartSource, /\.png\(\)/);
assert.match(apimartSource, /\.jpeg\(\{ quality/);
assert.match(apimartSource, /withoutEnlargement: true/);
assert.match(apimartSource, /Reference image upload exceeds APIMart 20MB limit after normalization/);
assert.match(apimartSource, /contentType: normalizedImage\.contentType/);
assert.match(apimartSource, /reference-upload/);
assert.match(apimartSource, /\/uploads\/images/);
assert.match(apimartSource, /extractApimartUploadUrl/);
assert.match(apimartSource, /uploadedReferenceImageUrls/);
assert.match(apimartSource, /image_urls:\s*uploadedReferenceImageUrls/);
assert.match(apimartSource, /extractApimartTaskId/);
assert.match(apimartSource, /extractApimartImageUrls/);
assert.match(apimartSource, /persistRemoteImage = false/);
assert.match(apimartSource, /return imageUrl/);
assert.match(apimartSource, /downloadRemoteImage/);

assert.match(compatSource, /OpenAI/);
assert.match(compatSource, /generateWithOpenAICompatible/);
assert.match(compatSource, /fallbackSize/);
assert.match(compatSource, /buildReferenceImageFile/);
assert.match(compatSource, /getLocalUploadPath/);
assert.match(compatSource, /referenceImage\.startsWith\("\/uploads\/"\)/);
assert.match(compatSource, /function getImageResult/);

assert.match(envExampleSource, /IMAGE_PROVIDER="apimart"/);
