import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const headerSource = readFileSync("src/components/layout/header.tsx", "utf8");
const appShellSource = readFileSync("src/components/layout/app-shell.tsx", "utf8");
const composerSource = readFileSync("src/components/generation/chat-composer.tsx", "utf8");
const homeSource = readFileSync("src/app/page.tsx", "utf8");
const historySource = readFileSync("src/app/history/page.tsx", "utf8");
const promptsSource = readFileSync("src/app/prompts/page.tsx", "utf8");
const redeemSource = readFileSync("src/app/redeem/page.tsx", "utf8");
const creditsSource = readFileSync("src/app/credits/page.tsx", "utf8");

assert.match(headerSource, /h-10 px-2 sm:h-8/);
assert.match(headerSource, /size-10[\s\S]*sm:size-8/);
assert.match(composerSource, /pb-\[calc\(env\(safe-area-inset-bottom\)\+0\.5rem\)\]/);
assert.match(composerSource, /mobileParameterSummary/);
assert.match(composerSource, /md:hidden/);
assert.match(composerSource, /hidden[\s\S]*md:flex/);
assert.match(composerSource, /hidden gap-3 md:flex md:flex-row md:items-end md:justify-between/);
assert.doesNotMatch(composerSource, /md:flex-col/);
assert.match(composerSource, /py-1\.5[\s\S]*sm:py-3/);
assert.match(composerSource, /max-h-24[\s\S]*md:max-h-40/);
assert.match(composerSource, /h-12 w-12[\s\S]*md:h-14 md:w-14/);
assert.match(composerSource, /overflow-x-auto[\s\S]*md:overflow-visible/);
assert.match(composerSource, /移动端生成参数/);
assert.match(composerSource, /已上传 \{referenceImages\.length\} 张参考图/);
assert.match(composerSource, /aria-label="打开生成参数"/);
assert.match(composerSource, /size-10[\s\S]*rounded-full/);
assert.match(appShellSource, /const isGenerationRoute = pathname === "\/" \|\| pathname === "\/generate"/);
assert.match(appShellSource, /isGenerationRoute[\s\S]*h-\[calc\(100svh-3\.5rem\)\] min-h-0 overflow-hidden md:h-\[calc\(100dvh-3\.5rem\)\]/);
assert.match(appShellSource, /: "min-h-\[calc\(100vh-3\.5rem\)\]"/);
assert.match(homeSource, /flex h-full min-h-0 flex-col overflow-hidden/);
assert.doesNotMatch(homeSource, /h-\[calc\(100svh-3\.5rem\)\]/);
assert.doesNotMatch(homeSource, /sticky bottom-0 z-20 shrink-0/);
assert.match(homeSource, /shrink-0/);
assert.match(homeSource, /md:static md:bg-transparent md:backdrop-blur-none/);
assert.match(homeSource, /min-h-0 flex-1 overflow-y-auto/);
assert.match(homeSource, /max-\[420px\]:flex-col/);
assert.match(homeSource, /max-\[420px\]:w-full/);
assert.match(homeSource, /max-\[420px\]:flex-row/);
assert.match(homeSource, /opacity-100[\s\S]*sm:opacity-0/);
assert.match(historySource, /min-\[380px\]:grid-cols-2/);
assert.match(historySource, /h-10/);
assert.match(promptsSource, /min-h-10/);
assert.match(redeemSource, /h-10/);
assert.match(creditsSource, /overflow-auto/);
